Nav in sidebar (BILA-009)
juanpernu/bilog-admin pull request #7
Opened 2021-03-29 13:48 UTC by DidierSoules

2021-03-29 15:00 UTC, RodriJOk approved these changes

2021-03-29 15:52 UTC, juanpernu commented on src/components/Sidebar/index.scss
> +      }
Si estas clases van a tener los mismos estilos, podrías unificarlas en una sola o simplemente eliminar el mod

2021-03-29 15:53 UTC, juanpernu commented on src/components/Sidebar/index.js
> +                    <span className="sidebar--links__documentation">
Esta class puede ser `sidebar--links` sin necesidad del mod, ya que los estilos para ambos links son los mismos.

2021-03-29 15:53 UTC, juanpernu commented on src/components/Sidebar/index.js
> +                    <span className="sidebar--links__posts">
Esta class puede ser `sidebar--links` sin necesidad del mod, ya que los estilos para ambos links son los mismos.

2021-03-29 15:55 UTC, juanpernu commented on src/components/Sidebar/index.scss
> +#toggle:focus {
Esto puede ser:
```
#toggle {
    &:hover,
    &:focus {
        ...props
    }
}

2021-03-29 15:55 UTC, juanpernu commented on src/components/Sidebar/index.scss
> +#closebtn {
Este id no no estas usando en ningun lado

2021-03-29 15:56 UTC, juanpernu commented on src/components/Sidebar/index.scss
> +.e-noraml:active {
Estas clases tampoco

2021-03-29 15:56 UTC, juanpernu commented on src/components/Sidebar/index.scss
> +}
Ojo con estos tags

2021-03-29 15:57 UTC, juanpernu requested changes
Hay que revisar bien los estilos del sidebar

2021-03-29 16:13 UTC, DidierSoules commented on src/components/Sidebar/index.scss
> +#toggle:focus {
@juanpernu , probé de esta manera que me comentas y no obtengo los mismos resultados. Queda el botón escondido en el header y al hacerle hover se mueve a la posición normal/anterior al cambio. Alguna idea porque?

2021-03-29 16:19 UTC, DidierSoules commented on src/components/Sidebar/index.scss
> +#toggle:focus {
![image](https://user-images.githubusercontent.com/36740732/112867371-38a61c00-9091-11eb-802e-bede7610d235.png)

Así funciona. Pero estoy repitiendo, lo cual no sabría si esta bien.

2021-04-08 01:46 UTC, juanpernu approved these changes

2021-04-08 01:46 UTC, merged